### ISSUE TITLE
珍珠玉：押韵问题

### ISSUE THREAD

**Issue by evestorm** [WillBeethoven/Poetry#1]
>痛苦刺激着石头，在内部分泌美玉

是不是与开头几句不那么押韵，要不要在不改变含义的情况下斟酌下用词。

**Comment by WillBeethoven** [comment]
@evestorm 修改了下 issue 的标题和其内容描述

有例子或建议吗？

**Comment by WillBeethoven** [comment]
目前没想到怎么改。
